# Generated by Django 6.0.2 on 2026-03-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_cgpa_remove_student_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='course',
        ),
    ]
