# Generated by Django 6.0.2 on 2026-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_mockinterviewquestion_mockinterviewsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='offer_date',
            field=models.DateField(blank=True, help_text='Date when candidate received an offer', null=True),
        ),
    ]
