# Generated by Django 6.0.2 on 2026-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, help_text='Student Resume PDF', null=True, upload_to='resumes/'),
        ),
    ]
