# Generated by Django 6.0.2 on 2026-03-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional bio', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile Picture Image', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.TextField(blank=True, help_text='Brief description of projects or comma separated', null=True),
        ),
    ]
