# Generated by Django 6.1 on 2026-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_bio_student_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('officer', 'Placement Officer'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
